"""
Generate TEAM_BRIEF.md in plain English from metrics/metrics.csv and
metrics/baseline_metrics.csv. Teammates open this file - no jargon.
Run any time: python scripts/team_brief.py (reads live data, safe during training)
"""

import csv
import os
from datetime import datetime, timezone

BASE = "/home/zeroij/mplads"
METRICS = f"{BASE}/metrics/metrics.csv"
BASELINE = f"{BASE}/metrics/baseline_metrics.csv"
OUT = f"{BASE}/TEAM_BRIEF.md"


def read_rows(path):
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def main():
    rows = read_rows(METRICS)
    base = read_rows(BASELINE)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# TEAM BRIEF (plain English, no jargon)",
        f"",
        f"Auto-generated by `scripts/team_brief.py` at **{now}**.",
        f"",
        f"## What we are doing",
        f"",
        f"We teach a language model (118M params, free open-source) to recognise when two "
        f"work descriptions in the MPLADS data are the **same work re-submitted as a new one** "
        f"('Bhavan' vs 'Bhawan', 'STANCH POST LIGHT' vs 'STAND POST LIGHTS'). This is the "
        f"'duplicate claim' part of our fraud detector.",
        f"",
        f"Training data: **70,607 real pairs** from our master file - 49,424 lessons (train), "
        f"10,591 practice exams (val), 10,592 final exams (test). Each lesson teaches it one "
        f"duplicate + one non-duplicate. Model: `paraphrase-multilingual-MiniLM-L12-v2`",
        f"",
        f"## Where things stand right now",
        f"",
    ]

    if not rows:
        lines += [
            f"### Training in progress - no lesson results yet",
            f"",
            f"- First results appear when lesson 1 of 4 finishes (each lesson / 'epoch' ≈ 25-35 min).",
            f"- Watch live: `python scripts/live_view.py`",
            f"- Log file: `run.log`",
            f"",
        ]
    else:
        lines += ["| Lesson # | Does it spot duplicates? (val %) | Finds the duplicate in top-20 (test %) | Train loss (lower = better) | Elapsed |", "|---|---|---|---|---|"]
        for r in rows:
            lines.append(
                f"| {r['epoch']} | {r['val_cosine_accuracy']} | {r['test_precision_at_k']} "
                f"| {r['train_loss']} | {r['elapsed_sec']}s |"
            )
        last = rows[-1]
        acc = float(last.get("val_cosine_accuracy") or 0)
        pk = float(last.get("test_precision_at_k") or 0)
        ep = last["epoch"]
        lines += [
            f"",
            f"### Plain-English verdict after lesson {ep}:",
            f"",
            f"- It **correctly rejects pure look-a-likes {acc:.1%}** of the time (higher = better).",
            f"- When it hunts through 10,592 works for the true duplicate, the right answer is in its "
            f"**top-20 picks {pk:.1%}** of the time.",
            f"- Baseline (before any training) to compare later: script `evaluate_after.py`.",
            f"- `{ep}` lessons done → model has seen the full dataset that many times. "
            + ("ALL LESSONS COMPLETE - model trained & saved." if ep == "4.0" else "More lessons = more sharpening."),
            f"",
        ]

    if base:
        lines += [
            f"## Frozen baseline (BEFORE training - captured, will not change)",
            f"",
            f"We scored the untrained model on 10 fixed 'expert' pairs so we can prove what training changed later.",
            f"",
        ]
        for r in base:
            lines.append(f"- **{r.get('name','?')}**: similarity {r.get('score','?')} (higher = more confident same work)")

    lines += [
        f"",
        f"## Honest scope (we told ourselves this)",
        f"",
        f"- Training sharpens **same-language, near-identical** duplicate detection ('Bhavan' vs 'Bhawan').",
        f"- It does **NOT** fix cross-language matching ('Shauchalaya' vs 'toilet') - the frozen model already "
        f"handles that; the data simply has no Hindi-English bridge pairs. That is a **data gap, not a "
        f"training failure**, and we will say so in the demo.",
        f"- The demo-critical fraud path (rules + anomaly detection + evidence dossier + legal note) uses the "
        f"frozen model and needs **zero training**. This fine-tune is the bonus slide.",
        f"",
        f"## Artifacts (where things live)",
        f"- Models: `models/best/epoch_<N>/` + `models/best/best.txt` (best pick)",
        f"- Results table: `metrics/metrics.csv`  |  Live watch: `scripts/live_view.py`",
        f"- Before/after comparison: `python scripts/evaluate_after.py`",
        f"- Raw training pairs: `data/pairs.csv`",
    ]

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()